### ISSUE TITLE
custom color scheme

### ISSUE THREAD

**Issue by bcclsn** [prateekmedia/netspeedsimplified#24] opened 2021-06-22 09:07 UTC
with the last update, there is a problem with custom color scheme, as you can see from the bottom image:

![immagine](https://user-images.githubusercontent.com/7371009/122896453-607fe580-d349-11eb-9f56-0a06f0f4984a.png)

I'm on GNOME Shell 40.2

**Comment by prateekmedia** [comment] 2021-06-22 09:08
> with the last update, there is a problem with custom color scheme, as you can see from the bottom image:
> 
> ![immagine](https://user-images.githubusercontent.com/7371009/122896453-607fe580-d349-11eb-9f56-0a06f0f4984a.png)
> 
> I'm on GNOME Shell 40.2

The problem is with? Color not applying to upload speed indicator?

**Comment by prateekmedia** [comment] 2021-06-22 09:18
You can now install the extension using the make install method given in resume, this issue should be fixed.

**Closed** 2021-06-22 09:17 UTC
