### ISSUE TITLE
Refresh Time keeps defaulting to 6.5

### ISSUE THREAD

**Issue by jenabaivab** [prateekmedia/netspeedsimplified#13] opened 2021-02-01 10:12 UTC
When I installed this extension, the refresh time was 1.5.
I tried to pull it to 1, and it went haywire. It keeps defaulting to 6.5 irrespective of how many times I change it now. 
Even reinstalling didn't help, since all the settings were preserved.

Running Debian Testing/unstable with Gnome 3.38.3

**Comment by prateekmedia** [comment] 2021-02-01 11:17
There is an option to reset settings to default in preferences you should use it, if it fixes then please report here.

**Comment by jenabaivab** [comment] 2021-02-01 13:47
Tried that already. Everything else is defaulted, but refreshs time defaults to 6.5 only

**Comment by prateekmedia** [comment] 2021-02-01 13:58
Can you post a screenshot of the Preference screen?

**Comment by prateekmedia** [comment] 2021-02-03 10:37
> Tried that already. Everything else is defaulted, but refreshs time defaults to 6.5 only

Can you post a screenshot of the Preference screen?

**Comment by jenabaivab** [comment] 2021-02-03 12:33
> > Tried that already. Everything else is defaulted, but refreshs time defaults to 6.5 only
> 
> Can you post a screenshot of the Preference screen?


![image](https://user-images.githubusercontent.com/60446763/106747573-17edb700-664a-11eb-96d1-a69ba0aa3bdc.png)

**Comment by prateekmedia** [comment] 2021-02-03 13:38
@jenabaivab As you can see the value of `Refresh Time` is not reset to the original as the *Refresh Time* is written in italic, the settings which are changed have that italic style. Unfortunately your provided info is too low, I can't find the cause by this only.

You can try this gist https://gist.github.com/balderclaassen/d12cfb70b1695c11402116d8b7f79059 it has the info of how to backup/reset extension data, replace the extension name by this extension name.

if it doesn't work then you can try the fork of this by other people's like m0hithreddy and other one by yukkeorg they only lack some new features but will have the same core principles as this one, but don't mess with it again.

**Comment by jenabaivab** [comment] 2021-02-03 16:18
@prateekmedia I know the value has been changed, the problem is it doesn't revert back anymore. I wanted to set it to 1s and not 1.5s. The moment i switched it, it just keeps reverting to 6.5 no matter how many times I change it. This is like an ultimatum not to touch anything, or it will just stop working. :/

**Comment by prateekmedia** [comment] 2021-03-06 17:08
> @prateekmedia I know the value has been changed, the problem is it doesn't revert back anymore. I wanted to set it to 1s and not 1.5s. The moment i switched it, it just keeps reverting to 6.5 no matter how many times I change it. This is like an ultimatum not to touch anything, or it will just stop working. :/

Any updates on this from your side?

**Comment by prateekmedia** [comment] 2021-03-24 17:09
Sorry @jenabaivab, you are right. The error is in the code due to reusing same variable names for spin buttons it thought that `refreshtime = minwidth` so it was getting reset to 6.5 which is the minimum width.

I will fix it eventually in the next updates with gnome 40.0 update.

**Comment by prateekmedia** [comment] 2021-03-26 13:48
This should be closed as everything is fine now

**Closed by prateekmedia** 2021-03-26 13:48 UTC
Labels: bug, good first issue
