### ISSUE TITLE
Not Working on GNOMe 42.4 on Fedora 36 Workstation

### ISSUE THREAD

**Issue by Raul1198** [prateekmedia/netspeedsimplified#41] opened 2022-10-01 12:33 UTC
this is what i get when i enable the extension

![image](https://user-images.githubusercontent.com/29801315/193409681-ed457a47-862c-454c-8a16-f52c14142e68.png)

it was also mentioned over simplenetspeed issue - https://github.com/biji/simplenetspeed/issues/37#issue-1387727536

**Comment by prateekmedia** [comment] 2022-10-01 16:06
Duplicate of #40, I will fix this till tomorrow

**Closed by prateekmedia** 2022-10-01 16:07 UTC
